fullnameOverride: scooter-rent


image:
  auth:
    repository: stkrizh/otus-arch
    tag: final-auth-service
  billing:
    repository: stkrizh/otus-arch
    tag: final-billing-service
  notification:
    repository: stkrizh/otus-arch
    tag: final-notification-service
  scooter:
    repository: stkrizh/otus-arch
    tag: final-scooter-management-service


service:
  type: ClusterIP
  port: 80


postgresql:
  fullnameOverride: postgres
  postgresqlUsername: user
  postgresqlPassword: passw
  postgresqlDatabase: dev


rabbitmq:
  fullnameOverride: rabbitmq
  auth:
    username: user
    password: passw
