apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-auth
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app: auth
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    app: auth


---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-profile
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app: profile
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    app: profile
