{
 "title": "Service",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"k8s-.*\", image!=\"\", container!=\"POD\"}[2m])",
     "legendFormat": "container={{container}}, pod={{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"k8s-.*\", image!=\"\", container!=\"POD\"}",
     "legendFormat": "container={{container}}, pod={{pod}}"
    }
   ]
  },
  { "title": "API methods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Latency by API method (0.99 quantile)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by (view, method, le) (rate(django_http_requests_latency_seconds_by_view_method_bucket[1m])))",
     "legendFormat": "method={{method}}, view={{view}}"
    }
   ]
  },
  {
   "title": "RPS by API method",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (view, method) (rate(django_http_requests_total_by_view_transport_method_total[2m]))",
     "legendFormat": "method={{method}}, view={{view}}"
    }
   ]
  },
  {
   "title": "Latency by API method (0.95 quantile)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (view, method, le) (rate(django_http_requests_latency_seconds_by_view_method_bucket[1m])))",
     "legendFormat": "method={{method}}, view={{view}}"
    }
   ]
  },
  {
   "title": "Error rate (HTTP 5xx)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum by (method, view) (increase(django_http_responses_total_by_status_view_method_total{status=~\"5..\"}[2m]))"
    }
   ]
  },
  {
   "title": "Latency by API method (0.5 quantile)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (view, method, le) (rate(django_http_requests_latency_seconds_by_view_method_bucket[1m])))",
     "legendFormat": "method={{method}}, view={{view}}"
    }
   ]
  },
  { "title": "Nginx Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Latency (0.99 quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(method, le) (rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"k8s-rest-service-chart\"}[2m])))"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum by (ingress) (rate(nginx_ingress_controller_requests{ingress=\"k8s-rest-service-chart\"}[2m]))"
    }
   ]
  },
  {
   "title": "Latency (0.95 quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(method, le) (rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"k8s-rest-service-chart\"}[2m])))"
    }
   ]
  },
  {
   "title": "Error rate (HTTP 5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Latency (0.5 quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(method, le) (rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"k8s-rest-service-chart\"}[2m])))"
    }
   ]
  }
 ]
}