version: "3.7"

services:
  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passw
      POSTGRES_DB: dev
    command: postgres -c max_connections=100 -c shared_buffers=200MB
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3.9.4-management-alpine
    ports:
      - 5672:5672
      - 15672:15672

  auth-service:
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    image: stkrizh/otus-arch:final-auth-service
    ports:
      - 8001:8080
    environment:
      POSTGRESQL_URL: "postgres://user:passw@postgres:5432/dev"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq/"

  billing-service:
    build:
      context: .
      dockerfile: billing_service/Dockerfile
    image: stkrizh/otus-arch:final-billing-service
    ports:
      - 8002:8081
    environment:
      POSTGRESQL_URL: "postgres://user:passw@postgres:5432/dev"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq/"

  notification-service:
    build:
      context: .
      dockerfile: notification_service/Dockerfile
    image: stkrizh/otus-arch:final-notification-service
    ports:
      - 8003:8082
    environment:
      POSTGRESQL_URL: "postgres://user:passw@postgres:5432/dev"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq/"

  scooter-management-service:
    build:
      context: .
      dockerfile: scooter_management_service/Dockerfile
    image: stkrizh/otus-arch:final-scooter-management-service
    ports:
      - 8004:8083
    environment:
      POSTGRESQL_URL: "postgres://user:passw@postgres:5432/dev"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq/"
